// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260318123712-00a90b7a03f4 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabXPbNhL+KxheZ5rMiXqzojj6cpNabqJc7Phs5zq92OdC5FJCAgIMAFpWPfrvNwvw",
	"VaQct5e4nk6/WcTLLnb3eXYX8K0XyDiRAoTR3uTWS6iiMRhQ9tcpaJmqAGbhCTVL/BKCDhRLDJPCm3jv",
	"BfucAmEhCMMiBorIiJglEJUt9Doe3NA44eBNvMFwD0bPxs992H8x9wfDcM+no2djfzQcjwejwfNRv9/3",
	"Oh7DnROU1/EEjXGlKvTwOp6CzylTEHoTo1LoeDpYQkxRuZjevAWxQE3Hex0vZiL/OejgjgYU7v3fD9T/",
	"te+/uHyS/eFf3vY748Em//70H995Hc+sE5StjWJi4W02m1yUNc2hUlI1LXL64wF5vt9/TtCsnFFhCOBM",
	"tEgihUaLJEomoAwD7dYbynhzp9dpTIWvgIZ0zoHATcKpoDhIdAIBi1hAjCRmyTSRQZAqBWLL4OdLIN+j",
	"Cb8nEQMeEqZJbj0yTw1ZUU2ENCRR8pqFEDZPje7QhuLOTe+fzoiCCKxgEknllCm0cwffoVvPjurePYMi",
	"kiqmxpt4qWJ+IbRNX22oSXWLPc/PT4gbJIEMa9qM+v1iJyYMLEDhVoYZ3nLus6VUhizr/tFpHFO1zgGQ",
	"KDnnENeOPBPXlLOQzESSmjbV3Ye7zZxhbc3EwgpyRrYrq7KWxiR60uuFQdzNvnYDGedWZ04Vn2Wq3Ne8",
	"myr8PniZWGeny2K2nH+EwOCJXgPlbcThvufu0EwsOBgpqrxRR0nSyj8HVEjBAsoJjt9JPkunCepPw3eC",
	"r3P6uH8AVXVu2Xv9RXMVS+1pGvbqeDc+hcQv9HfnRtbSuDw7wmXHS3iqKC8k45aFDQtaZGKRcqqqZ8/k",
	"JZwGEIMwXQwPJnvZBNT3FJbrUFEDp/A5BW1aKM4NkLkM1xb1ub5EZWtx3rYDBayu8olXLGxui2QlYFXu",
	"Npsiv6U6p5ZyfwirPv62rF/34PYp2mL+tOK++hF/TDmvWitRoEGYdoPRBFmZ8qtd8YgGyyflSKKRAWcr",
	"ZGHke4tza7L5mpxIzoI1ORQLJqB7HzAE1FAuF1fMQHyVp4Kd/kt31QPZNgS3IUVGqWJo/GL8bDAII38Q",
	"BXN/FI3H/j4Nn/kU5vvD/Whvf49iHqh7t6muAmrgyrC4xfznLAZtaJyQ1RJEjSpsJoyY0oa4LcIqKaL9",
	"fLvnPSzWZptmnZSH9On/USh93cD/4sHaKTg/gGPg8oS1A+Vmvne6/7IyrmJRV65C3NbqmMaQx94ZqGsW",
	"ADnJltQ0+5TO4Zop4w+Ge/dKDgkEFp1hyFAW5ScV1LpFW9VCJj4vi1wJF0nO5QqTuBSFpjpNEqkQqzpb",
	"hPIvRFZ2kif/PjpLIOiQAykMZQKU+zmlhs6pBvdLKnLAU23c6NPuhXC4qSo6aOGtNAl/P3Y41Ya4HX4v",
	"dLaodifzZE74zemzDMLbCoVvavm0mOPVEmgl2+xKocWUTSUFvGVtCfSELpiwlMyZNuj8qtjttHljrhK6",
	"gCsjP4FocQx+ztKwUQyu88IQVxJcmQlIualXLbB+k/znYDaefTxcHw3f94/Pf957+9P70bufZubo/M2n",
	"o/VgeTx9P3x7/q/18cefb46nh3vH05ero4M3L9qq1/IQk1sPvWb/+E5B5E28v/XKPrOXxXOvIL+i9vWo",
	"UnTdiIVy62bC3dgeJZIoLEBcBGjyzTYMpwdH5CR3Gnl5MiM+OUCqRzRSEZKYCrpwozIqeFl3L8Q5djW4",
	"gqHlcIa2Fi63i7hcEapJCBETEBJmEXIhUCiIJUaunYe+lZpyh0nOAsCOEN3s+tyXCQ2WQIZd5MBU8Uoh",
	"v1qtutQOd6Va9LK1uvd2dnB4fHboD7v97tLEvNK3eKWCR+XhXp7MvI53DUo7w1wPKE+WdIALZQKCJsyb",
	"eHvdfneUVarWj3mNOLn1FmB2VsfBEoJPNhzrBm8ogEFujT8LvYn3CszrskB3nbIVO+z3c8eCMFldxDMW",
	"7X3U0kKivAK4K9xe51VuIzje/dOGXNbDbZ0GY50uahU4Tu7V4r3VJqdgUiU0oU2gkxXDhiVxOYREjBuw",
	"QNq2DFLIaZUeKhc0HxoFpt0mb+cVsWGV3ah8TkGtyyuVpMyGpfUajLwt4IjesDiNiUjjuavuMmYhCcql",
	"i13iYnrjaEyzX6EmM4SIptx4kwE24bETkP9iIvvVbM+bypVUmDiGdWV16+lLRr3r/JffMBprOaIlJs/S",
	"IACto5STIiIQo6M7dcjuHf7+23Rxl1ktSvxAQ3tjhI2gHcx89VDy3wu4SSDAXAnZnCpM0XaEVpoqXQFr",
	"kZEvsV6UbZnYJgAgtNZ4di/EuwyXfJ2VbWtCScAZCONTrdkCSX42vRDXjNpU8AsLfyE2xkgB0C6ZRbXb",
	"tY5LCljbgSIrxjlZgEDXAqGCzKYuLdTx71SstAl3EkCuODbPZddcrG2DgquoHugO9dLlddDmBxmuvzqW",
	"XAjVL4g3DQwPvpHcHY1R1lDaIoNpMges0GxMYAaG8MFBnd9DVoA96o8fTn5+gaTgo4P29s2E0+jFw2l0",
	"IEXEWWCIX6BlNiWUY8eyxmou1YB9VeK0DLLpVs/h8OH0PDs5PSqze8aIqMPo4XTIPBVCAiIEEawtx8Vg",
	"yBMhS+U0cOvcp48xbxS8X23smmmjVuWVXeMs3LhUwsFAW9UXy+vq5hjfzGgymzbYfWr32M3ubYcvp/S2",
	"3uda6pXRHTc27gAh0UWlwdd/GBnNpvb6g7OcEEcPSUiZRTCSI5mK8LEg+7EBx8UrodmTzRfw02lvi16B",
	"wXpnGx7Z5XELSl6B+YYQ6T9IOfAoyvnHC7bHFug2Ru8X5buzxKR4sLJ3kbL9Nc2Ha8pTakAjKuCGaYMV",
	"YgEPuqBMaEPcM7pxRQizs8ML4apLvdXDuOuF7CHaNh9k6+mqS86XQCQPL0SxiOkiJ5QPSbitFHawmiiq",
	"FWxb31J5R/yayP0WvcPWg+e9eoj+A/UQxYMqoUEASdFHCLT/QoHWj6N9+OOz9V8dTNbBCFiV0PmrifnT",
	"NjEFcX25j8F19tbJEa97WejRhPXK2//LYmnjvartFr9ge938Nz2veTdbex5oW5v/C8rl5n8BAAD//6rt",
	"A0WTKAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
