// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZbXPbuBH+Kxj0Zu5uKurNiuLoSycn+RKmtuM69t1cY9UHkUsJCQggAGhJ59F/7wAg",
	"KdKkHefauPnQbyIJ7BuefXYXusWRSKXgwI3Gk1ssiSIpGFDu6Ry0yFQEYXxGzMq+iUFHikpDBccTfMnp",
	"pwwQjYEbmlBQSCTIrACpfCPuYNiQVDLAEzwYHsDo2fh5AIcvFsFgGB8EZPRsHIyG4/FgNHg+6vf7uIOp",
	"lSytvg7mJLU7VWkH7mAFnzKqIMYTozLoYB2tICXeeGNA2e3/ek+CP/rBi/kP+Y9gftvvjAe74v2Pf/sO",
	"d7DZSiteG0X5Eu92u0Ka8/5IKaGaTp//PEXPD/vPkY0co4QbBHaldVoKrq3TUgkJylDQfr8hlDUlvc5S",
	"wgMFJCYLBgg2khFO7EekJUQ0oREyApkV1UhEUaYU8DsxvVgB+t5G6XuUUGAxohoVAUKLzKA10YgLg6QS",
	"NzSGuOm1jbg2xEpuHvB5iBQk4BSjRChvTGmdd/we23ruq+498twToVJi8ARnigal0jZ7tSEm0y3xvLg4",
	"Q/4jikRcs2bU75eSKDewBGVFGWpYi9/vVkIZtKqfj87SlKhtgXGpxIJBWnM55DeE0RiFXGamzXT/4uEw",
	"5+m0pXzpFPkgu51VXStjpJ70enGUdvO33UikRdSpNyWguSmPDe+ummHvca7Wx2lerhaLDxAZ69FrIKyN",
	"G/z74jg05UsGRvAqNdSzRLZSzJRwwWlEGLLfH+SXlbfE2k/it5xtC4Z4PICqNrfI3raGqx6SDt4EBGRQ",
	"mrgnJm0Dmls572DJMkVYKdwqLMNUkhvly4wRVXUv1ycZiSAFbroWAVT08gXWpPOK8rqLP2eMleFDCqQC",
	"Ddw41mkcSUQMYWJ5TQ2k1/ezhCWh7L5SkMtAVgYqZVRjO34xfjYYxEkwSKJFMErG4+CQxM8CAovD4WFy",
	"cHhA+m25FCkgBq4NTdtsoiloQ1KJ1ivgNdA4Tkyo0gZ5EXE1PWJiIHAyHwEkGj+mKHreBHT+H1TFlGyO",
	"gS9tiowPOjilvHgcdL688H3WsfZkLBzwubj3sOZQEebH8v7ns1VCZG0hcUytIYSdVVDqN92hb1A3NIKy",
	"TvmamgjGxNqyquBQwFNnUgplIEY632T1X/G8D0A//HLyTkLUQVPBDaEclH+cEUMWRIN/EgpNWaaN//pj",
	"94rjFqrMZPznAcuINshL+LN4vUPt7dmdx3v+pbxWHvtt8euaxrsaz1VYu8Jrlbf3MVu5pMptx1SbZhjP",
	"yJJyGyPEqDb2lIvNukFvHDbmWpIlXBvxEXjLmdjXLn0VGEXhpijJdieyO3MFGTP1egHbN/Kf03Acfjja",
	"ngwv+6cXvx0c/3o5evtraE4u3nw82Q5Wp7PL4fHFP7anH37bnM6ODk5nL9cn0zcv2rhu78TkFtsDcz++",
	"U5DgCf5Lb9/E93Lg9kqy2VcoohTZtpQs1/hSngjH+RbnkY3s7m5azaYn6Kw4G/TyLEQBmloGtdlFeIxS",
	"wsnSfxVJSXe6e8UvbNtod1AbILtCu0DuxSVMrBHRKIaEcogRdTlwxa1S4CuLTbfOHqHQhPkcYzQC23Lb",
	"0/SzwktJohWgYddyS6ZYpVNar9dd4j53hVr28r26dxxOj07fHQXDbr+7MimrNIZ4b+DJ3rmXZyHu4BtQ",
	"2gfmZkCYXJGB3SgkcCIpnuCDbr87wp5L3XEVFXpyi5dg7m0/ohVEHx3q6gFvGGCx7IIfxniCX4F5ve+A",
	"/Cji1A77/eJggTu1REqWs2LvgxYO+fsx6iFUvS56jAY43v7dIStvku94YyFNlrX+xy7u1WDdGpNzMJni",
	"GpFmPqM1tR2h9DUBJZQZcPlyNzKWKc6rLFAZct83GiQnplYNiqH0UwZqu59K80/7wDXo9q7sE7KhaZYi",
	"nqUL3yHl3IEkKMcn96hKycYTlaZ/1HXGkJCMGTwZ2AEn9QqKJ8rzp+bo0zRuT3bSc6jvCNvMqXDmQ/7P",
	"vyIQa1WgBY7vsigCrZOMoRIMNj1HD9qQz3R//TJb/EVBixE/kdhN46Bd/S/P6qn0X3LYSIhsNYR8TTVD",
	"bewQqcwDupKnZc2d23ZQtNVax/2ACOKwLmV0r/jbPCXZNu/AtoigiFHgJiBa06Xl93CGrvgNJa4M/E7j",
	"35EDGSqTs4vCpHZ10fEFwWYmKLSmjKElcHu2gAhH4cyXhHruexsrnfeDyV9Ybq0ruvZKf9KWCzTGD9xB",
	"feEF1Nx3aKDNTyLe/teTxWOkfoG2ayTp4CvprYc6zBvOcgZ76uQs7mr8BYnT/uLptE8FTxiNDApKgIUz",
	"RJht4be2+cm0a91Gw+HTGfWLDYhv52ATgSxI81sjrpJ4qrNDk7dqHcZ+LgnjnecyBgbaOo5U3FSFo8UW",
	"UaNROGuwy8zJuJ9d2pzfL+nduV9vKZijB4Zw70CMdFnq2PZ/lkXhzI3SjBaZPHo6G8qI2GqRiIzH3yJo",
	"PVYQye9CP4PdTns7/AqMrXV3oZnfvrUg9BWYrwjP/pOUim+il/s/0B8LdIfRx6HcbXT9nAekn9d7RNLe",
	"fqael1sblz1ts3EJEd38AxE3x57a0N22t7hWn+/+HQAA//93nMNxLR0AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
