// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260318123712-00a90b7a03f4 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabXPbNhL+KxheZ9rOiXqzojj6cpNabqNc7Phs5zq92OdC5FJCAgIMAFpSPfrvNwvw",
	"VaQcN5e4+ZBvFgnsLhb7PPtC33mBjBMpQBjtTe68hCoagwFlf52DlqkKYBaeUbPEJyHoQLHEMCm8ifdG",
	"sA8pEBaCMCxioIiMiFkCUdlGr+PBmsYJB2/iDYYHMHoyfurD4bO5PxiGBz4dPRn7o+F4PBgNno76/b7X",
	"8RhKTlBfxxM0xp2qsMPreAo+pExB6E2MSqHj6WAJMUXjYrp+BWKBlo4POl7MRP5z0EGJBhTK/u9b6v/R",
	"959d/5D94V/f9TvjwTZ//uM/vvM6ntkkqFsbxcTC2263uSrrmmOlpGp65PznI/L0sP+UoFs5o8IQwJXo",
	"kUQKjR5JlExAGQba7TeU8aakF2lMha+AhnTOgcA64VRQfEl0AgGLWECMJGbJNJFBkCoFYsfhl0sg36ML",
	"vycRAx4SpknuPTJPDVlRTYQ0JFHyloUQNk+N16ENRcnN2z+fEQURWMUkksoZU1jnDr7Htp59q3sPDIpI",
	"qpgab+KlivmF0jZ7taEm1S3+vLw8I+4lCWRYs2bU7xeSmDCwAIWiDDO85dwXS6kMWdbvR6dxTNUmB0Ci",
	"5JxDXDvyTNxSzkIyE0lq2kx3D+53c4a1DRMLq8g52e6s6loak+hJrxcGcTd72g1knHudOVN8lpnyUPdu",
	"q/B762VqnZ+ui9Vy/g4Cgyd6AZS3EYd7nl+HZmLBwUhR5Y06SpJW/jmiQgoWUE7w/b3ks3SWoP00fC34",
	"JqePhwdQ1eYW2ZuPuqvYak/T8FfHW/sUEr+w350bWUvj9uwI1x0v4amivNCMIgsfFrTIxCLlVFXPnulL",
	"OA0gBmG6GB5M9rIFaO85LDehogbO4UMK2rRQnHtB5jLcWNTn9hKV7cV1uxcoYHWTL7xhYVMskpWAVSlt",
	"NkV+S3VOLaV8CKt3/GVZv36Du6doi/nzyvXVj/hzynnVW4kCDcK0O4wmyMqU3+yLR3RYvihHEo0MOF8h",
	"CyPfW5xbl8035ExyFmzIsVgwAd2HgCGghnK5uGEG4ps8Fey9v3RfPZCJISiGFBmliqHxs/GTwSCM/EEU",
	"zP1RNB77hzR84lOYHw4Po4PDA4p5oH67TXMVUAM3hsUt7r9kMWhD44SsliBqVGEzYcSUNsSJCKukiP7z",
	"rcwHeKzNN806KQ/p8/+jUPq8gf/Rg7VTcH4Ax8DlCWsHyt384HT/cWNcxaJuXIW4a9UpjSGPvQtQtywA",
	"cpZtqVn2Pp3DLVPGHwwPHpQcEggsOsOQoS7KzyqodZt2qoVMfV4WuRIukpzLFSZxKQpLdZokUiFWdbYJ",
	"9V+JrOwkP/z75CKBoEOOpDCUCVDu55QaOqca3C+pyBFPtXFvf+xeCYebqqGDFt5Kk/DTscOpNsRJ+FTo",
	"7FDtXubJLuFPp88yCO8qFL6t5dNijVdLoJVssy+FFku2lRTwirUl0DO6YMJSMmfa4OVX1e6mzbW5SegC",
	"box8D6LlYvBxloaNYnCbF4a4k+DOTEHKTb1qgc3L5D9Hs/Hs3fHmZPimf3r528GrX9+MXv86MyeXL9+f",
	"bAbL0+mb4avLf21O3/22Pp0eH5xOn69Ojl4+a6tey0NM7jy8NfvHdwoib+L9rVf2mb0snnsF+RW1r0eV",
	"optGLJSimwl3a3uUSKKyAHERoMu3uzCcHp2Qs/zSyPOzGfHJEVI9opGKkMRU0IV7K6OCl3X3SlxiV4M7",
	"GHoOV2jr4VJcxOWKUE1CiJiAkDCLkCuBSkEsMXLtOrxbqSl3mOQsAOwI8Zpdn/s8ocESyLCLHJgqXink",
	"V6tVl9rXXakWvWyv7r2aHR2fXhz7w26/uzQxr/QtXmngSXm452czr+PdgtLOMbcDypMlHeBGmYCgCfMm",
	"3kG33x1llaq9x7xGnNx5CzB7q+NgCcF7G451hzcMwCC3zp+F3sT7BcyLskB3nbJVO+z384sFYbK6iGcs",
	"2nunpYVEOQK4L9xe5FVuIzhe/9OGXNbD7ZwGY50uahU4Lu7V4r3VJ+dgUiU0oU2gkxXDhiVxOYREjBuw",
	"QNr1DFLIeZUeKgOat40C04rJ23lFbFhlE5UPKahNOVJJymxYeq/ByLsKTuiaxWlMRBrPXXWXMQtJUC9d",
	"7FMX07WjMc3+gJrOECKacuNNBtiEx05B/ouJ7FezPW8aV1Jh4hjWldWtpy8Z9b7zX3/BaKzliJaYvEiD",
	"ALSOUk6KiECMju61IZs7/P3P2eKGWS1G/ERDOzHCRtC+zO7qsfS/EbBOIMBcCdmaKkzRd4RWmipdAWuR",
	"ka+xXpRtmdgmACC01nh2r8TrDJd8k5VtG0JJwBkI41Ot2QJJfja9EreM2lTwOwt/JzbGSAHQLplFtela",
	"xyUFrO1AkRXjnCxA4NUCoYLMpi4t1PHvTKy0CfcSQG44Ns9l11zsbYOCq6geaYZ67fI6aPOTDDefHUsu",
	"hOoD4m0Dw4MvpHdPY5Q1lLbIYJrMASs0GxOYgSF8dFDnc8gKsEf98ePpzwdICt45aO9OJpxFzx7PoiMp",
	"Is4CQ/wCLbMpoRw7lg1Wc6kG7KsSZ2WQLbd2DoePZ+fF2flJmd0zRvz6aLmg1Wrf1GTlWhFVNmWzcOuY",
	"moOBtqIqlrdV4Rg+zGgymzbIc2pl7CfPtsOXS3o7n79ayoHRPQMRd4CQ6CKR881fhvXZ1E4XOMv5ZvSY",
	"eM88gskwkqkIvwGnHTguXgnNvoh8BD+d9q7jFzBYTuzCI5vNtqDkFzBfECL9R8m2X0W1/PWC7WsLdBuj",
	"D4vy/VliUnwPsqM+2f6xyodbylNqQCMqYM20wQKsgAddUCa0Ie4rtXE5ntnV4ZVwxZveaRFc955957W1",
	"Pdn5MtQll0sgkodXotjEdJETyu80KFYK+7KaKKoFYltbUPlM9zmR+yVK853viQ8q0fuPVKIX3ysJDQJI",
	"ijJdoP8XCrT+Oqrzvz5bf2sQsgZBwKqEzrce4VMzQMELH28TcJ+dmThec3PxHk1Yr5xdXxdbG19b2mbQ",
	"BZnq5j+Zec3JYm243bY3/weK6+3/AgAA//9mRpsPUScAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
